// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRhJu_VkSHL8isBPM3_-958Njg1HeqQ_s',
    appId: '1:969405997458:web:a28a687e26dc37c035a14b',
    messagingSenderId: '969405997458',
    projectId: 'chat-29183',
    authDomain: 'chat-29183.firebaseapp.com',
    storageBucket: 'chat-29183.appspot.com',
    measurementId: 'G-W5ESSQJJ5Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDES_HIHG8bsUjV8g3UHBmzc2LDxTJl8Og',
    appId: '1:969405997458:android:00196d5d78c9742035a14b',
    messagingSenderId: '969405997458',
    projectId: 'chat-29183',
    storageBucket: 'chat-29183.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjF_bXNU2iN9B4EuE3gXL5SIB92fOs5lA',
    appId: '1:969405997458:ios:06848441b9bffe9635a14b',
    messagingSenderId: '969405997458',
    projectId: 'chat-29183',
    storageBucket: 'chat-29183.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjF_bXNU2iN9B4EuE3gXL5SIB92fOs5lA',
    appId: '1:969405997458:ios:06848441b9bffe9635a14b',
    messagingSenderId: '969405997458',
    projectId: 'chat-29183',
    storageBucket: 'chat-29183.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRhJu_VkSHL8isBPM3_-958Njg1HeqQ_s',
    appId: '1:969405997458:web:0f6762796287112835a14b',
    messagingSenderId: '969405997458',
    projectId: 'chat-29183',
    authDomain: 'chat-29183.firebaseapp.com',
    storageBucket: 'chat-29183.appspot.com',
    measurementId: 'G-KJZJE2CL20',
  );
}
